services:
  destructivefarm:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: destructivefarm
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/ferma
    ports:
      - 9000:5000
    command: |
      sh -c "cd server && flask --app standalone.py run --host=0.0.0.0 --with-threads"
networks: {}
